### PR TITLE
Move to Bindgen for Sys Crate

### PR DESCRIPTION
**Pull request by iwillspeak**
Move to `bindgen` for the `onig_sys` crate. This should help us better track changes in the Oniguruma API.

Fixes: #104, #103, #100, #96

### CODE REVIEW

**Comment by iwillspeak** [comment]
This is now pretty much complete. It switches from the manually-maintained bindings to `bindgen` generated ones. This should help with bugs related to changes in the Oniguruma internal representation of expressions.

Because there's no proper exposure of the collection of names and indices for matching in the stable Oniguruma API this branch drops support for the `CaptureNames` and relies entriely on the `foreach_name` method.

**Comment by iwillspeak** [comment]
Apologies for leaving this a bit abandoned, I'm currenlty in the process or moving house. @defuz are you happy with the proposed changes and releasing them as `onig` 5.0? @ignatenkobrain Would you be able to test with this branch to see if it fixes the issues you were seeing?

**Comment by iwillspeak** [comment]
Apologies for leaving this a bit abandoned, I'm currenlty in the process or moving house. @defuz are you happy with the proposed changes and releasing them as `onig` 5.0? @ignatenkobrain Would you be able to test with this branch to see if it fixes the issues you were seeing?

**Comment by iwillspeak** [comment]
Apologies for leaving this a bit abandoned, I'm currenlty in the process or moving house. @defuz are you happy with the proposed changes and releasing them as `onig` 5.0? @ignatenkobrain Would you be able to test with this branch to see if it fixes the issues you were seeing?

**Comment by kornelski** [comment]
I've tested this branch, and it fixes the crash I was hitting:

```text
* thread #2, name = 'rayon-6', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x00000001006dcd8e crate_pages`onigenc_is_mbc_newline_0x0a(p=0x0000000000000000, end="") at regenc.c:686:12 [opt]
    frame #1: 0x00000001006c1aa7 crate_pages`match_at(reg=<unavailable>, str=<unavailable>, end="", in_right_range="", sstart="Try", sprev=<unavailable>, msa=0x0000700001674ac0) at regexec.c:3228:16 [opt]
    frame #2: 0x00000001006c5e71 crate_pages`onig_search_with_param(reg=0x000000014e2b4b10, str=<unavailable>, end="", start="Try", range="", region=0x0000700001674d70, option=0, mp=0x000000014e2b54e0) at regexec.c:4815:7 [opt]
    frame #3: 0x00000001006bc306 crate_pages`onig::Regex::search_with_param::hdc32d6247841fbd7(self=0x000000014e2b6ac0, chars=<unavailable>, from=<unavailable>, to=123145325858040, options=(bits = 0), region=Option<&mut onig::region::Region> @ 0x0000700001674c78, match_param=MatchParam @ 0x0000700001674c80) at lib.rs:693:12 [opt]
    frame #4: 0x00000001006bc166 crate_pages`onig::Regex::search_with_encoding::hf62ff134c81cefcf(self=<unavailable>, chars=<unavailable>, from=<unavailable>, to=<unavailable>, options=(bits = 0), region=Option<&mut onig::region::Region> @ 0x0000700001674d60) at lib.rs:624:21 [opt]
    frame #5: 0x00000001006bc4be crate_pages`onig::Regex::find_with_encoding::h4875bbc574460501(self=0x000000014e2b6ac0, text=<unavailable>) at lib.rs:777:8 [opt]
    frame #6: 0x00000001006bc45e crate_pages`onig::Regex::find::h3ff7c848fdda3f41(self=<unavailable>, text=<unavailable>) at lib.rs:753:8 [opt]
    frame #7: 0x00000001006b59d2 crate_pages`syntect::parsing::syntax_set::SyntaxSet::find_syntax_by_first_line::h52ff29d203a8b2dd(self=0x000000014e2a8440, s=(data_ptr = "Try", length = 3)) at syntax_set.rs:192:15 [opt]
```

**Pull request merged**
