### PR TITLE
Fix the bindgen-take-two branch

### PR DESCRIPTION
**Pull request by Keats**
Waiting for CI now...

### CODE REVIEW

**Comment by Keats** [comment]
@iwillspeak this is now passing for appveyor but it seems Travis is not running? Did they change something again and the repo needs to be enabled or something?

**Comment by Keats** [comment]
@iwillspeak ping

**Comment by kornelski** [comment]
@Keats ping! The bindgen dependency is a huge PITA, so I'm anxious to see this and #126 released.

**Comment by Keats** [comment]
I'm not a maintainer, I can't do anything :/
I'll push a new crate next week otherwise since I am also blocked on the bindgen issue

**Pull request merged**
