### PR TITLE
derive eq and partialeq for region and regex

### PR DESCRIPTION
**Pull request by TyOverby**

### CODE REVIEW

**Comment by trishume** [comment]
I've oftentimes wanted Regex&Region to implement Eq, if only so that I can derive Eq in other structs that include a Regex. 👍

**Comment by trishume** [comment]
ping @iwillspeak, I think this might not have notified him

**Comment by iwillspeak** [comment]
Thanks for the ping. Missed this one somehow. This looks good at first glance. I'll take a closer look and merge when I'm back at a computer.

**Comment by iwillspeak** [comment]
Thanks for this. :sparkles: **merged** :sparkles:

**Pull request merged**
